package com.froggyeye.honestsignal

/**
 * Maps a theme name, a 0..5 score and the high-contrast preference to the
 * drawable that the status-bar notification uses as its small icon.
 *
 * Pre-rendered vector drawables rather than a bitmap built at runtime: the
 * system renders resource small icons through its own monochrome tinting path
 * on every Android version and OEM skin, which a runtime bitmap is not
 * guaranteed to survive. Thirty-six tiny XML files buy that certainty; they are
 * generated by `android/tools/generate_indicator_icons.py`, which is where the
 * geometry and the reasoning behind the plate live.
 *
 * Theme names match `BarTheme` in Dart; the geometry matches
 * `lib/shared/widgets/signal_bars.dart`.
 */
object IndicatorIcons {

    private val BARS = intArrayOf(
        R.drawable.ic_signal_bars_0,
        R.drawable.ic_signal_bars_1,
        R.drawable.ic_signal_bars_2,
        R.drawable.ic_signal_bars_3,
        R.drawable.ic_signal_bars_4,
        R.drawable.ic_signal_bars_5,
    )

    private val BARS_PLATE = intArrayOf(
        R.drawable.ic_signal_bars_plate_0,
        R.drawable.ic_signal_bars_plate_1,
        R.drawable.ic_signal_bars_plate_2,
        R.drawable.ic_signal_bars_plate_3,
        R.drawable.ic_signal_bars_plate_4,
        R.drawable.ic_signal_bars_plate_5,
    )

    private val DOTS = intArrayOf(
        R.drawable.ic_signal_dots_0,
        R.drawable.ic_signal_dots_1,
        R.drawable.ic_signal_dots_2,
        R.drawable.ic_signal_dots_3,
        R.drawable.ic_signal_dots_4,
        R.drawable.ic_signal_dots_5,
    )

    private val DOTS_PLATE = intArrayOf(
        R.drawable.ic_signal_dots_plate_0,
        R.drawable.ic_signal_dots_plate_1,
        R.drawable.ic_signal_dots_plate_2,
        R.drawable.ic_signal_dots_plate_3,
        R.drawable.ic_signal_dots_plate_4,
        R.drawable.ic_signal_dots_plate_5,
    )

    private val WAVE = intArrayOf(
        R.drawable.ic_signal_wave_0,
        R.drawable.ic_signal_wave_1,
        R.drawable.ic_signal_wave_2,
        R.drawable.ic_signal_wave_3,
        R.drawable.ic_signal_wave_4,
        R.drawable.ic_signal_wave_5,
    )

    private val WAVE_PLATE = intArrayOf(
        R.drawable.ic_signal_wave_plate_0,
        R.drawable.ic_signal_wave_plate_1,
        R.drawable.ic_signal_wave_plate_2,
        R.drawable.ic_signal_wave_plate_3,
        R.drawable.ic_signal_wave_plate_4,
        R.drawable.ic_signal_wave_plate_5,
    )

    fun resourceFor(theme: String?, bars: Int, highContrast: Boolean = true): Int {
        val level = bars.coerceIn(0, 5)
        return when (theme) {
            "dots" -> if (highContrast) DOTS_PLATE[level] else DOTS[level]
            "wave" -> if (highContrast) WAVE_PLATE[level] else WAVE[level]
            else -> if (highContrast) BARS_PLATE[level] else BARS[level]
        }
    }
}
