#!/usr/bin/env python3
"""Generates the status-bar indicator drawables.

Run from the repo root:

    python3 android/tools/generate_indicator_icons.py

Writes `android/app/src/main/res/drawable/ic_signal_*.xml`, and with
`--preview` also writes SVG copies to a directory for eyeballing at size.

Why a generator: there are three indicator themes, six score levels and two
contrast variants, so 36 files whose geometry must agree with each other, with
`SignalBubbleView.kt` and with `lib/shared/widgets/signal_bars.dart`. Hand-
editing 36 files is how one of them ends up 0.2dp out.

The two variants
----------------
*plain* — the original mark: lit elements at full alpha, unlit at 0.28. It is
elegant and it is what a status bar of solid colour wants.

*plate* — the high-contrast variant, and the default from 1.0.1. Android tints
a status-bar small icon with a single colour and uses the drawable purely as an
alpha mask, so there is no second colour to contrast against a wallpaper with.
The only lever left is *mass*: a filled plate at mid alpha carries the mark and
the lit elements sit on it at full alpha, separated from it by a transparent
moat cut out of the plate. Every pixel of the mark is then adjacent to a
different alpha, which survives any wallpaper underneath and reads as a distinct
object rather than as five loose strokes — and it is a silhouette the system's
own radio bars never have.

An unlit element gets its moat but keeps its interior at plate alpha, so it
reads as an empty outlined slot. Cutting the whole slot out was the first
design and it was wrong: a hole shows the wallpaper, and over a pale patch of
wallpaper an *empty* bar lit up as brightly as a full one. Nothing behind the
icon may be allowed to carry meaning.

The one thing no alpha mask can do is stay visible where the wallpaper happens
to match the tint the system chose. The plate mitigates it — a larger mark is
more likely to overlap a contrasting patch — but it cannot be solved from here.
"""

from __future__ import annotations

import argparse
import math
import os

VIEWPORT = 24.0

# Plate geometry, in viewport units.
PLATE_INSET = 0.4
PLATE_RADIUS = 6.2
GLYPH_INSET = 2.3  # from the plate edge to the glyph's own 24-unit box
MOAT = 0.42  # how far each cut-out is dilated past the shape it holds

PLATE_ALPHA = 0.44
LIT_ALPHA = 1.0
UNLIT_ALPHA = 0.28  # plain variant only; the plate variant leaves a hole

WHITE = "#FFFFFFFF"
NONE = "#00000000"

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by android/tools/generate_indicator_icons.py — do not edit.
     Status-bar small icons are alpha masks: the system picks the colour, so
     these carry shape and alpha only. {variant_note} -->
"""

PLAIN_NOTE = "Lit elements full alpha, unlit dimmed."
PLATE_NOTE = (
    "High-contrast variant: a mid-alpha plate with the mark cut out of it, so "
    "the glyph reads against any wallpaper."
)


def fmt(value: float) -> str:
    """Trims float noise so the generated files are stable across runs."""
    text = f"{value:.3f}".rstrip("0").rstrip(".")
    return "0" if text in ("", "-0") else text


# ---------------------------------------------------------------------------
# Shape geometry. Each theme returns, for a level, the list of element outlines
# in draw order. An element is (kind, params) so it can be rendered either as a
# drawn shape or as a dilated cut-out.
# ---------------------------------------------------------------------------


def bars_elements() -> list[dict]:
    out = []
    for i in range(5):
        out.append(
            {
                "kind": "rect",
                "x": 1.5 + i * 4.4,
                "y": 15.0 - i * 3.25,
                "w": 3.4,
                "h": 6.0 + i * 3.25,
            }
        )
    return out


def dots_elements() -> list[dict]:
    out = []
    for i in range(5):
        out.append(
            {
                "kind": "circle",
                "cx": 3.0 + i * 4.5,
                "cy": 14.5,
                "r": 1.5 + i * 0.28,
            }
        )
    return out


def wave_elements() -> list[dict]:
    # A filled dot at the origin plus four concentric arcs over it.
    out = [{"kind": "circle", "cx": 12.0, "cy": 20.0, "r": 1.7}]
    for i in range(1, 5):
        out.append(
            {
                "kind": "arc",
                "cx": 12.0,
                "cy": 20.0,
                "r": 3.1 * i + 1.5,
                "stroke": 2.1,
                "start": 135.0,
                "end": 45.0,
            }
        )
    return out


THEMES = {
    "bars": bars_elements,
    "dots": dots_elements,
    "wave": wave_elements,
}


# ---------------------------------------------------------------------------
# Path emission
# ---------------------------------------------------------------------------


def transform(element: dict, scale: float, offset: float) -> dict:
    """Maps an element from the bare 24-unit box into the plate's inner box."""

    def sx(v: float) -> float:
        return offset + v * scale

    out = dict(element)
    if element["kind"] == "rect":
        out.update(
            x=sx(element["x"]),
            y=sx(element["y"]),
            w=element["w"] * scale,
            h=element["h"] * scale,
        )
    elif element["kind"] == "circle":
        out.update(cx=sx(element["cx"]), cy=sx(element["cy"]), r=element["r"] * scale)
    else:
        out.update(
            cx=sx(element["cx"]),
            cy=sx(element["cy"]),
            r=element["r"] * scale,
            stroke=element["stroke"] * scale,
        )
    return out


def rect_path(x: float, y: float, w: float, h: float) -> str:
    return f"M{fmt(x)},{fmt(y)} h{fmt(w)} v{fmt(h)} h{fmt(-w)} z"


def circle_path(cx: float, cy: float, r: float) -> str:
    return (
        f"M{fmt(cx - r)},{fmt(cy)} "
        f"a{fmt(r)},{fmt(r)} 0 1,0 {fmt(2 * r)},0 "
        f"a{fmt(r)},{fmt(r)} 0 1,0 {fmt(-2 * r)},0 z"
    )


def arc_point(cx: float, cy: float, r: float, degrees: float) -> tuple[float, float]:
    rad = math.radians(degrees)
    return cx + r * math.cos(rad), cy - r * math.sin(rad)


def arc_stroke_path(element: dict) -> str:
    """The arc as a stroked path — used for the drawn (lit) element."""
    x0, y0 = arc_point(element["cx"], element["cy"], element["r"], element["start"])
    x1, y1 = arc_point(element["cx"], element["cy"], element["r"], element["end"])
    r = fmt(element["r"])
    return f"M{fmt(x0)},{fmt(y0)} A{r},{r} 0 0,1 {fmt(x1)},{fmt(y1)}"


def arc_outline_path(element: dict, dilate: float) -> str:
    """The same arc as a closed outline, for cutting it out of the plate.

    Sampled rather than built from four SVG arc commands: the sweep/large-arc
    flags for the two round caps are easy to get subtly wrong and impossible to
    see at 24dp, whereas a polygon at 3-degree steps is obviously right and
    costs a few hundred bytes.
    """
    cx, cy, r = element["cx"], element["cy"], element["r"]
    half = element["stroke"] / 2 + dilate
    start, end = element["start"], element["end"]
    steps = max(6, int(abs(start - end) / 3))

    def cap(degrees: float, outward: int) -> list[tuple[float, float]]:
        """Half-circle round cap at [degrees], swung [outward] along travel."""
        px, py = arc_point(cx, cy, r, degrees)
        rad = math.radians(degrees)
        # Radial unit vector (towards the outer edge) and the direction of
        # travel along the arc, both in screen coordinates.
        ux, uy = math.cos(rad), -math.sin(rad)
        tx, ty = math.sin(rad), math.cos(rad)
        out = []
        for i in range(1, 9):
            phi = math.pi * i / 8
            cos_p, sin_p = math.cos(phi) * outward, math.sin(phi) * outward
            out.append((px + half * (cos_p * ux + sin_p * tx),
                        py + half * (cos_p * uy + sin_p * ty)))
        return out

    points: list[tuple[float, float]] = []
    # Outer edge, start -> end.
    for i in range(steps + 1):
        deg = start + (end - start) * i / steps
        points.append(arc_point(cx, cy, r + half, deg))
    points += cap(end, 1)
    # Inner edge, end -> start.
    for i in range(steps + 1):
        deg = end + (start - end) * i / steps
        points.append(arc_point(cx, cy, r - half, deg))
    points += cap(start, -1)

    head = f"M{fmt(points[0][0])},{fmt(points[0][1])}"
    rest = " ".join(f"L{fmt(x)},{fmt(y)}" for x, y in points[1:])
    return f"{head} {rest} z"


def outline_path(element: dict, dilate: float) -> str:
    """The element's outline, grown by [dilate], as one closed subpath."""
    if element["kind"] == "rect":
        return rect_path(
            element["x"] - dilate,
            element["y"] - dilate,
            element["w"] + 2 * dilate,
            element["h"] + 2 * dilate,
        )
    if element["kind"] == "circle":
        return circle_path(element["cx"], element["cy"], element["r"] + dilate)
    return arc_outline_path(element, dilate)


def cutout_subpaths(element: dict, lit: bool) -> list[str]:
    """What this element contributes to the plate's even-odd path.

    A lit element cuts a hole the size of itself plus the moat, which the drawn
    element then fills back in leaving the moat as a transparent ring. An unlit
    element cuts the same hole and immediately restores its own interior — one
    more even-odd crossing — leaving only the moat, so the empty slot is drawn
    as an outline and never lets the wallpaper stand in for a lit bar.
    """
    subpaths = [outline_path(element, MOAT)]
    if not lit:
        subpaths.append(outline_path(element, 0.0))
    return subpaths


def rounded_rect_path(inset: float, radius: float) -> str:
    a, b, r = inset, VIEWPORT - inset, radius
    return (
        f"M{fmt(a + r)},{fmt(a)} "
        f"H{fmt(b - r)} A{fmt(r)},{fmt(r)} 0 0,1 {fmt(b)},{fmt(a + r)} "
        f"V{fmt(b - r)} A{fmt(r)},{fmt(r)} 0 0,1 {fmt(b - r)},{fmt(b)} "
        f"H{fmt(a + r)} A{fmt(r)},{fmt(r)} 0 0,1 {fmt(a)},{fmt(b - r)} "
        f"V{fmt(a + r)} A{fmt(r)},{fmt(r)} 0 0,1 {fmt(a + r)},{fmt(a)} z"
    )


def draw_element(element: dict, alpha: float) -> str:
    if element["kind"] == "rect":
        data = rect_path(element["x"], element["y"], element["w"], element["h"])
    elif element["kind"] == "circle":
        data = circle_path(element["cx"], element["cy"], element["r"])
    else:
        return (
            f'    <path android:strokeColor="{WHITE}" android:strokeAlpha="{fmt(alpha)}"\n'
            f'        android:strokeWidth="{fmt(element["stroke"])}" '
            f'android:strokeLineCap="round"\n'
            f'        android:fillColor="{NONE}" '
            f'android:pathData="{arc_stroke_path(element)}"/>\n'
        )
    return (
        f'    <path android:fillColor="{WHITE}" android:fillAlpha="{fmt(alpha)}"\n'
        f'        android:pathData="{data}"/>\n'
    )


def vector(body: str, note: str) -> str:
    return (
        HEADER.format(variant_note=note)
        + '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp"\n'
        '    android:height="24dp"\n'
        '    android:viewportWidth="24"\n'
        '    android:viewportHeight="24">\n'
        + body
        + "</vector>\n"
    )


def plain_drawable(theme: str, level: int) -> str:
    elements = THEMES[theme]()
    body = "".join(
        draw_element(e, LIT_ALPHA if i < level else UNLIT_ALPHA)
        for i, e in enumerate(elements)
    )
    return vector(body, PLAIN_NOTE)


def plate_drawable(theme: str, level: int) -> str:
    scale = (VIEWPORT - 2 * (PLATE_INSET + GLYPH_INSET)) / VIEWPORT
    offset = PLATE_INSET + GLYPH_INSET
    elements = [transform(e, scale, offset) for e in THEMES[theme]()]

    # One even-odd path: the plate, with each element's moat cut out of it.
    # Even-odd is what turns the inner subpaths into holes rather than more
    # plate, and it is also what lets an unlit slot restore its own interior
    # with a second, nested subpath.
    subpaths = [rounded_rect_path(PLATE_INSET, PLATE_RADIUS)]
    for i, element in enumerate(elements):
        subpaths += cutout_subpaths(element, lit=i < level)
    body = (
        f'    <path android:fillColor="{WHITE}" android:fillAlpha="{fmt(PLATE_ALPHA)}"\n'
        f'        android:fillType="evenOdd"\n'
        f'        android:pathData="{" ".join(subpaths)}"/>\n'
    )
    body += "".join(draw_element(e, LIT_ALPHA) for e in elements[:level])
    return vector(body, PLATE_NOTE)


# ---------------------------------------------------------------------------
# SVG preview (design iteration only; nothing ships from here)
# ---------------------------------------------------------------------------


def svg_preview(xml: str, background: str) -> str:
    """Re-renders a generated vector as SVG so it can be viewed at size."""
    body = xml.split(">\n", 1)[1]
    body = body[body.index("<path") :].replace("</vector>", "")
    body = (
        body.replace("android:fillColor", "fill")
        .replace("android:strokeColor", "stroke")
        .replace("android:fillAlpha", "fill-opacity")
        .replace("android:strokeAlpha", "stroke-opacity")
        .replace("android:strokeWidth", "stroke-width")
        .replace("android:strokeLineCap", "stroke-linecap")
        .replace("android:fillType", "fill-rule")
        .replace("android:pathData", "d")
        # currentColor so a preview page can tint the mask the way the system
        # does: white on a dark status bar, near-black on a light one.
        .replace('"#FFFFFFFF"', '"currentColor"')
        .replace('"#00000000"', '"none"')
        .replace("evenOdd", "evenodd")
    )
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" '
        'viewBox="0 0 24 24">'
        f'<rect width="24" height="24" fill="{background}"/>{body}</svg>'
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out",
        default="android/app/src/main/res/drawable",
        help="drawable directory to write",
    )
    parser.add_argument("--preview", help="also write SVG previews here")
    parser.add_argument(
        "--preview-bg", default="#101418", help="preview background colour"
    )
    args = parser.parse_args()

    os.makedirs(args.out, exist_ok=True)
    if args.preview:
        os.makedirs(args.preview, exist_ok=True)

    written = 0
    for theme in THEMES:
        for level in range(6):
            for suffix, xml in (
                (f"ic_signal_{theme}_{level}", plain_drawable(theme, level)),
                (f"ic_signal_{theme}_plate_{level}", plate_drawable(theme, level)),
            ):
                with open(os.path.join(args.out, f"{suffix}.xml"), "w") as handle:
                    handle.write(xml)
                written += 1
                if args.preview:
                    with open(
                        os.path.join(args.preview, f"{suffix}.svg"), "w"
                    ) as handle:
                        handle.write(svg_preview(xml, args.preview_bg))
    print(f"wrote {written} drawables to {args.out}")


if __name__ == "__main__":
    main()
