/// Fixed strings that also appear in store metadata. Keep them identical to
/// what release-manager writes into `ios/fastlane/metadata/` and
/// `android/fastlane/metadata/android/` — a privacy URL that differs between
/// the binary and the listing is a store-review finding.
class AppConstants {
  const AppConstants._();

  static const String appName = 'Honest Signal';
  static const String publisher = 'Froggy Eye Ltd';

  /// House convention (house-facts #5), GitHub Pages variant: the **rendered
  /// HTML** of the repo's `PRIVACY_POLICY.md`, regenerated by
  /// `scripts/build_privacy_html.py`. Not the raw Markdown URL — GitHub serves
  /// that as `text/plain`, which App Review has treated as not being a privacy
  /// policy page (5.1.1(i)). Must return 200 as `text/html` before submission.
  static const String privacyPolicyUrl =
      'https://mksoft-ltd.github.io/honest_signal/privacy_policy.html';

  static const String supportUrl = 'https://honestsignal.froggyeye.com';

  static const String supportEmail = 'info@froggyeye.com';
}
